### PR TITLE
Feat/postpage

### PR DESCRIPTION
**Pull request by joshuahuerto2**

### CODE REVIEW

**Comment by joshuahuerto2** [comment]
Works in both light and dark mode

image
image

**Review by jamestang12 — CHANGES_REQUESTED** [review]
Please follow Figma design, remove all extra white space at the back, update text-align to left and we are not using color mode as we discussed during the stand-up meeting

**Comment by joshuahuerto2** [comment]
image

**Comment by joshuahuerto2** [comment]
Fixed metadata font and text alignment

image

**Comment by jamestang12** [comment]
I am currently working on this pr, please lmk if anyone is making commit to this branch

**Comment by jamestang12** [comment]
I have commit all the latest changes, feel free to edit/work on this branch

**Review by patel1643 — APPROVED** [review]

**Pull request merged**
