### PR TITLE
Images fetch feature

### PR DESCRIPTION
**Pull request by patel1643**
- added dynamic image fetching on reload
- added more info support for image (tags, categories, etc)
- updated files according to the Image type
- updated image, user and store interfaces according to new rules
- updated upload modal for user hints
- updated photo card component to accomodate new changes

### CODE REVIEW

**Comment by Mwpereira** [comment]
image

should maybe put a little bit of margin between the label and the image, just a tiny bit more

**Comment by Mwpereira** [comment]
image

can we hide the overflow/scroll on windows

**Comment by patel1643** [comment]
> image
> 
> can we hide the overflow/scroll on windows

lol I can't figure out

**Comment by Mwpereira** [comment]
image

can we update the Filters button to show the current filter if a user selects one

**Comment by Mwpereira** [comment]
image

can you add a little bit of margin below the image, just a tiny bit

**Comment by Mwpereira** [comment]
image

Should we make the information text a little bit bigger?

**Comment by Mwpereira** [comment]
We should remove Categories under the image information

**Comment by Mwpereira** [comment]
Location is not shown and overflow of tags is handled correctly

image

**Review by Mwpereira — CHANGES_REQUESTED** [review]
Requested Changes

**Pull request merged**
